name: Build and Push Backend to Harbor and Update GitOps

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"

env:
  HARBOR_URL: harbor.seokmin.com
  HARBOR_PROJECT: test
  NEXT_PUBLIC_API_URL: https://test.seokmin.com
  GITOPS_REPO: seokmingg/hybrid-cloud
  GITOPS_PATH: helm/service/test-hybrid/test-hybrid-app/values-canary.yaml

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set dynamic image tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/backend:${{ env.IMAGE_TAG }}
          build-args: |
            JWT_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            FRONTEND_URL=${{ env.NEXT_PUBLIC_API_URL }}
            BACKEND_URL=${{ env.NEXT_PUBLIC_API_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DBNAME=${{ secrets.POSTGRES_DBNAME }}
            POSTGRES_HOST=test-hybrid-postgresql-ha-pgpool.test.svc.cluster.local

      - name: Clone GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gitops

      - name: Install yq (YAML parser)
        run: sudo snap install yq

      - name: Update image tag in GitOps repo
        run: |
          cd gitops
          yq e '.backend.image.tag = "${{ env.IMAGE_TAG }}"' -i ${{ env.GITOPS_PATH }}

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git commit -am "ci: Update backend image tag to ${{ env.IMAGE_TAG }}"
          git push origin main