name: Build and Push Backend to Harbor

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"

env:
  HARBOR_URL: harbor.seokmin.com
  HARBOR_PROJECT: test
  IMAGE_TAG: latest
  NEXT_PUBLIC_API_URL: https://test.seokmin.com

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/backend:${{ env.IMAGE_TAG }}
          build-args: |
            JWT_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            FRONTEND_URL=${{ env.NEXT_PUBLIC_API_URL }}
            BACKEND_URL=${{ env.NEXT_PUBLIC_API_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DBNAME=${{ secrets.POSTGRES_DBNAME }}
            POSTGRES_HOST=test-hybrid-postgresql-ha-pgpool.test.svc.cluster.local